CREATE TABLE warnings (
    id INT AUTO_INCREMENT PRIMARY KEY,
    task_id INT,
    stream_id INT,
    algorithm_id INT,
    warning_type VARCHAR(50) NOT NULL COMMENT '告警类型：入侵检测、人脸识别等',
    level INT DEFAULT 1 COMMENT '1:低级, 2:中级, 3:高级',
    image_path VARCHAR(255),
    warning_metadata TEXT COMMENT 'JSON格式的告警详细信息',
    status VARCHAR(20) DEFAULT 'new' COMMENT 'new:新告警, processing:处理中, resolved:已解决, ignored:已忽略',
    processed_by INT,
    processed_at DATETIME,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (task_id) REFERENCES monitor_tasks (id),
    FOREIGN KEY (stream_id) REFERENCES video_streams (id),
    FOREIGN KEY (algorithm_id) REFERENCES algorithms (id),
    FOREIGN KEY (processed_by) REFERENCES users (id),
    INDEX idx_task_id (task_id),
    INDEX idx_stream_id (stream_id),
    INDEX idx_algorithm_id (algorithm_id),
    INDEX idx_warning_type (warning_type),
    INDEX idx_level (level),
    INDEX idx_status (status),
    INDEX idx_created_at (created_at)
);